#!/bin/sh

##################################################################
##
##  proxy-restrict-firewall
##  Configure Qubes firewall for use with a proxy such as OpenVPN.
##
##  Note: For customization, add rules to a filename in firewall.d
##  other than '90_proxy-restrict'.
##
##################################################################

# Set firewall restriction policy

# Stop all leaks between downstream (vif+) and upstream (Internet eth0):
iptables -P FORWARD DROP
iptables -I FORWARD -o eth0 -j DROP
iptables -I FORWARD -i eth0 -j DROP

ip6tables -P FORWARD DROP
ip6tables -I FORWARD -o eth0 -j DROP
ip6tables -I FORWARD -i eth0 -j DROP

# Block INPUT from proxy(s):
iptables -P INPUT DROP
iptables -I INPUT -i tun+ -j DROP

ip6tables -P INPUT DROP
ip6tables -I INPUT -i tun+ -j DROP

# Allow established v6 traffic (v4 rule already present):
#iptables -A INPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT

# Disable icmp packets
#if iptables -C INPUT -p icmp -j ACCEPT
#then iptables -D INPUT -p icmp -j ACCEPT
#fi
